name: Release
on: push
jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # os: [macos-latest, ubuntu-latest, windows-latest]
        os: [macos-latest]

    steps:
    - uses: actions/checkout@v2       
    - uses: actions/setup-node@master
      with:
        node-version: 18
    - name: install dependencies
      run: npm install
    - name: build
      run: npm run app:build
    - name: release
      run: run release
      # uses: softprops/action-gh-release@v1
      # if: startsWith(github.ref, 'refs/tags/')
      # with:
      #   files: "dist_electron/(*.exe,*.deb,*.zip,*.dmg)"
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
